### PR TITLE
Add KNIME

### LINKED ISSUE #19: Add KNIME
https://www.knime.com/

### PR DESCRIPTION
**Pull request by cricket007**
Closes #19

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Is KNIME actually open-source? I couldn't find a license after a quick search.

**Comment by cricket007** [comment]
> Is KNIME actually open-source

The core is - https://github.com/knime

**Comment by gunnarmorling** [comment]
Ok, I see. Perhaps let's link to that repo then? These kinds of open core
projects are a bit tricky to capture right, and I'd like to avoid "muddying
the water" of this list which should be solely limited to OSS projects.

>

**Comment by gunnarmorling** [comment]
Thanks for clarifying! And thanks a lot for all the nice additions, much appreciated!

Let me know if you'd like to add more things to this Awesome List, I can make you a committer if you like.

**Comment by cricket007** [comment]
I'll add more as I think of them 

Wouldn't mind being a commiter ☺️

**Comment by gunnarmorling** [comment]
Cool, just sent you an invite :)

**Pull request merged**
