### PR TITLE
Remove Heron

### PR DESCRIPTION
**Pull request by MRazaKazmi**
Removing Heron from the Stream Processing section.

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Interesting, why should it be removed?

**Comment by MRazaKazmi** [comment]
It retired on 2023-01-18 and is no longer active.

**Review by gunnarmorling — APPROVED** [review]
LGTM, merged. Thx!

**Comment by gunnarmorling** [comment]
Gotcha! Thanks!

**Pull request merged**
