### PR TITLE
Add SQS to messaging infra

### PR DESCRIPTION
**Pull request by Chloejay**

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Hey @Chloejay, thanks for the PR, but I don't think SQS is open-source, or is it?

**Comment by OneCricketeer** [comment]
I would suggest changing this with Localstack

https://github.com/localstack/localstack

**Comment by Chloejay** [comment]
> Hey @Chloejay, thanks for the PR, but I don't think SQS is open-source, or is it?

@gunnarmorling this service is closed source, thanks for pointing out. sorry I did a false commit I think.

**Comment by Chloejay** [comment]
> I would suggest changing this with Localstack
> 
> https://github.com/localstack/localstack

checked, I think this is a good option in local machine. thanks @OneCricketeer

**Pull request closed without merging**
